[target.'cfg(all(target_arch = "arm", target_os = "none"))']

# set runner for cargo
runner = "probe-run --chip STM32F407VGTx"

# custom linker flags for ARM target
rustflags = [
  "-C", "linker=flip-link", # flip-link stack-overflow protection
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tdefmt.x", # for defmt logger
]

[build]
# target = "thumbv6m-none-eabi"    # Cortex-M0 and Cortex-M0+
# target = "thumbv7m-none-eabi"    # Cortex-M3
# target = "thumbv7em-none-eabi"   # Cortex-M4 and Cortex-M7 (no FPU)
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[env]
DEFMT_LOG = "debug" # default log level for defmt
